name: "MetasploitSight sighting client"

services:

  nucleivuln-client:
    image: vuln_lookup_metasploitsight-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_IMAGE=python:3.11-slim
    restart: always
    environment:
      - PYTHONUNBUFFERED=TRUE
      - METASPLOITSIGHT_CONFIG=/etc/conf.py
    volumes:
      - "./metasploitsight/conf.py:/etc/conf.py"
