VULNERABILITY_LOOKUP_BASE_URL = "https://vulnerability.circl.lu/"
VULNERABILITY_LOOKUP_AUTH_TOKEN = ""

GIT_REPOSITORY = "metasploit-repository"

SIGHTING_TYPE = "seen"


# Hearbeat mechanism
HEARTBEAT_ENABLED = True
VALKEY_HOST = "127.0.0.1"
VALKEY_PORT = 10002
EXPIRATION_PERIOD = 18000
